version: '3'

dotenv: ['.env']

tasks:
  build:
    cmds:
      - cmd: env GOOS=linux GOARCH=arm64 go build -o ./bin/linux-arm64/display-driver .     
        platforms: [linux/arm64] 
      - cmd: env GOOS=linux GOARCH=arm go build -o ./bin/linux-arm/display-driver .
        platforms: [linux/arm]
      - cmd: env GOOS=darwin go build -o ./bin/darwin/display-driver .
        platforms: [darwin]
      - cmd: env GOOS=linux GOARCH=x86_64 go build -o ./bin/linux-x86_64/display-driver .

