version: '3'

dotenv: ['.env']

tasks:
  install:
    platforms: [linux/arm64, linux/arm]
    cmds:
      - cp "$BINARY_PATH" "$INSTALL_PATH"
      - sudo chmod +x "$INSTALL_PATH"
      - | 
          bash -c "cat > $SERVICE_FILE" <<EOF
          [Unit]
          Description=OLED Display Service
          After=network.target

          [Service]
          Type=simple
          ExecStart=$INSTALL_PATH
          Restart=on-failure
          User=$USER
          WorkingDirectory=/
          Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

          [Install]
          WantedBy=multi-user.target
          EOF
      - sudo systemctl daemon-reexec
      - sudo systemctl daemon-reload
      - sudo systemctl enable "$SERVICE_NAME"
      - sudo systemctl start "$SERVICE_NAME"
  uninstall:
    platforms: [linux/arm64, linux/arm]
    cmds:
      - systemctl stop "$SERVICE_NAME"
      - rm $INSTALL_PATH
      - rm $SERVICE_FILE
      - systemctl daemon-reexec
      - systemctl daemon-reload
  update:
    platforms: [linux/arm64, linux/arm]
      cmds:
        - cp "$BINARY_PATH" "$INSTALL_PATH"
        - sudo systemctl restart "$SERVICE_NAME"
  build:
    cmds:
      - cmd: env GOOS=darwin go build -o ./bin/darwin/display-driver .
        platforms: [darwin]
      - cmd: env GOOS=linux GOARCH=arm64 go build -o ./bin/arm/display-driver .
        platforms: [linux/arm64, linux/arm]
  build-darwin:
      - cmd: env GOOS=darwin go build -o ./bin/darwin/display-driver .
  build-arm:
      - cmd: env GOOS=linux GOARCH=arm64 go build -o ./bin/arm/display-driver .
