version: '3'

dotenv: ['.env']

tasks:
  build:
    cmds:
      - cmd: env GOOS=darwin go build -o ./bin/darwin/display-driver .
        platforms: [darwin]
      - cmd: env GOOS=linux GOARCH=amd64 go build -o ./bin/linux/display-driver .
        platforms: [linux/arm64, linux/arm, linux/amd64]

